### ISSUE TITLE
MySQL with UTF8MB4: Specified key was too long

### ISSUE THREAD

**Issue by grote** [arteria/django-background-tasks#103]
When using this library with a MySQL database that is using the `UTF8MB4` character set, you get this error when migrating the database schema:

```
  Applying background_task.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

If possible, fields that have an index should be limited to `190` characters instead of `255`.

Similar issue: pennersr/django-allauth#1450

**Comment by walterrenner** [comment]
Seems like the fix from django-allauth is pretty simple and straightforward. @grote do you mind providing a PR base on the fix from django-allauth?

**Comment by grote** [comment]
If there are not technical reasons from your side to limit the length of those fields to `190`, I can do that.

**Comment by walterrenner** [comment]
I dont't think there is a technical reason. PullRequest would great 👍
