### ISSUE TITLE
You can't execute queries until the end of the 'atomic' block.  

### ISSUE THREAD

**Issue by user008811** [arteria/django-background-tasks#118]
Hello,
looks like this one is back in 1.11, or maybe it was not completely fixed.
https://github.com/arteria/django-background-tasks/issues/46

Nothing special on my usage side, just a function which reads massive amount of models and compares data.
Django 1.11.5 on Python 2.7.14 on Heroku.

2017-10-07T19:43:15.200806+00:00 app[scheduler.3354]: Traceback (most recent call last):
2017-10-07T19:43:15.200824+00:00 app[scheduler.3354]:   File "manage.py", line 10, in <module>
2017-10-07T19:43:15.200828+00:00 app[scheduler.3354]:     execute_from_command_line(sys.argv)
2017-10-07T19:43:15.200829+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
2017-10-07T19:43:15.200881+00:00 app[scheduler.3354]:     utility.execute()
2017-10-07T19:43:15.200881+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
2017-10-07T19:43:15.201032+00:00 app[scheduler.3354]:     self.fetch_command(subcommand).run_from_argv(self.argv)
2017-10-07T19:43:15.201033+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
2017-10-07T19:43:15.201089+00:00 app[scheduler.3354]:     self.execute(*args, **cmd_options)
2017-10-07T19:43:15.201090+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
2017-10-07T19:43:15.201161+00:00 app[scheduler.3354]:     output = self.handle(*args, **options)
2017-10-07T19:43:15.201162+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/management/commands/process_tasks.py", line 94, in handle
2017-10-07T19:43:15.201190+00:00 app[scheduler.3354]:     if not self._tasks.run_next_task(queue):
2017-10-07T19:43:15.201191+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/tasks.py", line 134, in run_next_task
2017-10-07T19:43:15.201220+00:00 app[scheduler.3354]:     return self._runner.run_next_task(self, queue)
2017-10-07T19:43:15.201221+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
2017-10-07T19:43:15.201320+00:00 app[scheduler.3354]:     return func(*args, **kwargs)
2017-10-07T19:43:15.201321+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/tasks.py", line 260, in run_next_task
2017-10-07T19:43:15.201365+00:00 app[scheduler.3354]:     self.run_task(tasks, task)
2017-10-07T19:43:15.201365+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
2017-10-07T19:43:15.201403+00:00 app[scheduler.3354]:     return func(*args, **kwargs)
2017-10-07T19:43:15.201404+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/tasks.py", line 251, in run_task
2017-10-07T19:43:15.201448+00:00 app[scheduler.3354]:     tasks.run_task(task)
2017-10-07T19:43:15.201449+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/tasks.py", line 131, in run_task
2017-10-07T19:43:15.201475+00:00 app[scheduler.3354]:     self._bg_runner(proxy_task, task, *args, **kwargs)
2017-10-07T19:43:15.201476+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/tasks.py", line 59, in bg_runner
2017-10-07T19:43:15.201496+00:00 app[scheduler.3354]:     task.reschedule(t, e, traceback)
2017-10-07T19:43:15.201496+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/models.py", line 236, in reschedule
2017-10-07T19:43:15.201539+00:00 app[scheduler.3354]:     self.increment_attempts()
2017-10-07T19:43:15.201540+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/models.py", line 221, in increment_attempts
2017-10-07T19:43:15.201579+00:00 app[scheduler.3354]:     self.save()
2017-10-07T19:43:15.201580+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/background_task/models.py", line 310, in save
2017-10-07T19:43:15.201627+00:00 app[scheduler.3354]:     return super(Task, self).save(*arg, **kw)
2017-10-07T19:43:15.201628+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 807, in save
2017-10-07T19:43:15.201741+00:00 app[scheduler.3354]:     force_update=force_update, update_fields=update_fields)
2017-10-07T19:43:15.201742+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 837, in save_base
2017-10-07T19:43:15.201861+00:00 app[scheduler.3354]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
2017-10-07T19:43:15.201862+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 904, in _save_table
2017-10-07T19:43:15.201990+00:00 app[scheduler.3354]:     forced_update)
2017-10-07T19:43:15.201991+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 954, in _do_update
2017-10-07T19:43:15.202124+00:00 app[scheduler.3354]:     return filtered._update(values) > 0
2017-10-07T19:43:15.202125+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 664, in _update
2017-10-07T19:43:15.202224+00:00 app[scheduler.3354]:     return query.get_compiler(self.db).execute_sql(CURSOR)
2017-10-07T19:43:15.202226+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1199, in execute_sql
2017-10-07T19:43:15.202395+00:00 app[scheduler.3354]:     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
2017-10-07T19:43:15.202396+00:00 app[scheduler.3354]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
2017-10-07T19:43:15.202528+00:00 app[scheduler.3354]:     raise original_exception
2017-10-07T19:43:15.202540+00:00 app[scheduler.3354]: django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

**Comment by user008811** [comment]
Found the source of the problem: If any call in the function fails (create in this case) transaction probably aborts and its reported as this.
