### ISSUE TITLE
django2.0 not working

### ISSUE THREAD

**Issue by uixdk** [arteria/django-background-tasks#121]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/compat/models.py", line 3, in <module>
    from compat import GenericForeignKey
ImportError: cannot import name 'GenericForeignKey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./web.py", line 35, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.5/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/background_task/models.py", line 10, in <module>
    from compat.models import GenericForeignKey
  File "/usr/local/lib/python3.5/dist-packages/compat/models.py", line 5, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/contenttypes/fields.py", line 3, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/contenttypes/models.py", line 134, in <module>
    class ContentType(models.Model):
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by walterrenner** [comment]
Thanks for reporting. Your error isn't specific to Django 2.0. Add `'django.contrib.contenttypes',` to your INSTALLED_APPS list and try again.

Bisides that error there might be more. We're not supporting Django2.0 yet.

**Comment by walterrenner** [comment]
Test suite is passing with Django 2.0. I'll close this issue. Please feel free to open a new issue if you encounter any other problems related to Django 2.0.

**Comment by sanderzz91** [comment]
Then it may be a good idea to update the Django version support mentioned in http://django-background-tasks.readthedocs.io/en/latest/#supported-versions-and-compatibility?-. 

I was looking for a competitor for celery and almost dropped django-background-tasks as an alternative because of the compatibility mentioned in the docs made me think it wasn't ready for Django 2.

**Comment by bschollnick** [comment]
Hey, this seems to be happening again?

INSTALLED_APPS = [
    'wq1',
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'background_task',
    'frontend',
]

In my tasks.py:

@background(schedule=30)
def check_q():
    logger.debug("checking the queues - %s" % time.ctime())
    print ("checking the queues")
    
If I comment out the background line, everything starts up fine.  So I'm stumped...

       - Benjamin


Am I missing something here?  I've been fighting this for an hour or so, with no luck.  

Django starts up fine
Running on bschollnicklt
wq1 init
Running on bschollnicklt
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x038E5738>
Traceback (most recent call last):
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\compat\models.py", line 3, in <module>
    from compat import GenericForeignKey
ImportError: cannot import name 'GenericForeignKey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\core\management\commands\runserver.py", line 11
2, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_e
xception
    raise _exception[1]
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\core\management\__init__.py", line 327, in exec
ute
    autoreload.check_errors(django.setup)()
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\bschollnick\python3\workqueues\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\bschollnick\Documents\wq1\frontend\__init__.py", line 3, in <module>
    import frontend.tasks
  File "C:\Users\bschollnick\Documents\wq1\frontend\tasks.py", line 8, in <module>
    @background(schedule=30)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task\__init__.py", line 7, in background
    from background_task.tasks import tasks
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task\tasks.py", line 16, in <module>
    from background_task.models import Task
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task\models.py", line 10, in <module>
    from compat.models import GenericForeignKey
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\compat\models.py", line 5, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\contrib\contenttypes\fields.py", line 3, in <mo
dule>
    from django.contrib.contenttypes.models import ContentType
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\contrib\contenttypes\models.py", line 134, in <
module>
    class ContentType(models.Model):
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\db\models\base.py", line 100, in __new__app_config = apps.get_containing_app_config(module)
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
