### ISSUE TITLE
BACKGROUND_TASK_RUN_ASYNC = True not executing any task

### ISSUE THREAD

**Issue by doctor-yes** [arteria/django-background-tasks#124]
I use django-background-tasks with my Django project, the tasks check on certain files with sleep and take action as a file appears. Everything is working fine but I want the tasks to be executed asynchronously so that missing one file will not lock up everything else, so I went into setting.py to add

BACKGROUND_TASK_RUN_ASYNC = True

Looks like django-background-tasks just stop executing any task. Once I set:

BACKGROUND_TASK_RUN_ASYNC = False

it starts executing, synchronously... What am I missing? Thank you.

**Comment by walterrenner** [comment]
Could you please provide more information.

* What versions of django and django-background-tasks are you using?
* What do you mean by "just stop executing any task" is the process terminated or are no tasks picked from the DB and the process is just idle?
* You see any logging outputs? There should be entries when a tasks is picked from the DB and when django-backgorund-tasks starts to process this task. You see anny diffrence in the logfiles when you process synchronously and asynchronously

**Comment by philippeowagner** [comment]
@doctor-yes any news for us?

**Comment by benjaminmathews** [comment]
I saw the same issue two weeks back. Switched it to False, because it was a production server, and async functionality was not important. Tried recreating now, but it doesn't seem to have that issue right now. So, this may not be an issue in django-background-tasks itself. Still looking into possible causes.

**Comment by benjaminmathews** [comment]
For what it's worth, responses to the earlier questions: 
1. I was running background-tasks v1.1.10 on Django v1.11.7 on Python v2.7.12
2. In the scenario, process is running, but not picking up any tasks and is just idle
3. No logging outputs, however, I did not do a comprehensive check of the log files

**Comment by manishtripathiitt** [comment]
Hi, i am also facing the same issue

**Comment by philippeowagner** [comment]
@manishtripathiitt could you provide more info. Thanks.

**Comment by manishtripathiitt** [comment]
@philippeowagner  Thanks for your help. issue was related to the Django upgrade to new version in my project and i resolved the issue and it seems it working fine now.

**Comment by toinuma** [comment]
A similar phenomenon occurred with the following setting. 
"BACKGROUND_TASK_RUN_ASYNC = True"
Exit with "django.db.utils.OperationalError".

My versions..
・Python 3.6.0
・Django 1.11.5
・django-background-tasks 1.1.13

```
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/background_task/management/commands/process_tasks.py", line 94, in handle
    if not self._tasks.run_next_task(queue):
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/background_task/tasks.py", line 134, in run_next_task
    return self._runner.run_next_task(self, queue)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/contextlib.py", line 52, in inner
    with self._recreate_cm():
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/db/transaction.py", line 184, in __enter__
    connection.set_autocommit(False, force_begin_transaction_with_broken_autocommit=True)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/db/backends/base/base.py", line 411, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 307, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 307, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/MySQLdb/connections.py", line 257, in autocommit
    _mysql.connection.autocommit(self, on)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```
