### ISSUE TITLE
conflict with other third party libraries which are having tasks.py files

### ISSUE THREAD

**Issue by jab3z** [arteria/django-background-tasks#137]
Hi!

I was trying to configure the library, but it seems it's a conflict with [django dbmail](https://github.com/LPgenerator/django-db-mailer) 

> ./manage.py process_tasks
DEBUG    [raven.contrib.django.client.DjangoClient:270] Configuring Raven for host: https://sentry.mykuwaitnet.net
DEBUG    [raven.contrib.django.client.DjangoClient:721] Sending message of length 3948 to https://sentry.mykuwaitnet.net/api/87/store/
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/background_task/management/commands/process_tasks.py", line 85, in handle
    autodiscover()
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/background_task/tasks.py", line 313, in autodiscover
    import_module("%s.tasks" % app)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/dacian/.virtualenvs/alnajaat/lib/python2.7/site-packages/dbmail/tasks.py", line 4, in <module>
    from celery import task
ImportError: No module named celery

I have identified the problem, it's because tasks.autodiscover function iterates over all INSTALLED_APPS with no possibility to define apps which shall be excluded.

I propose a solution to create a setting variable `BACKGROUND_TASK_EXCLUDED_APPS` and excluding apps if added in BACKGROUND_TASK_EXCLUDED_APPS

`def autodiscover():
    """
    Autodiscover tasks.py files in much the same way as admin app
    """
    import imp
    from django.conf import settings

    for app in settings.INSTALLED_APPS:
        if app in settings.BACKGROUND_TASK_EXCLUDED_APPS:
            continue
        else:
            try:
                app_path = import_module(app).__path__
            except (AttributeError, ImportError):
                continue
            try:
                imp.find_module('tasks', app_path)
            except ImportError:
                continue

            import_module("%s.tasks" % app)`

I can submit PR with it, if you like the idea.

**Comment by davidzwa** [comment]
👍
