### ISSUE TITLE
Cannot import name 'GenericForeignKey' (see issue 121)

### ISSUE THREAD

**Issue by bschollnick** [arteria/django-background-tasks#145]
Hey, this seems to be potentially related to Issue # 121?  

With this configuration I am seeing crashes if I try to establish a background task...  It'll error with an "Import error: Cannot import name 'GenericForeignKey'", but django.ctronib.contenttypes is in my installed_apps list...

INSTALLED_APPS = [
'wq1',
'django.contrib.contenttypes',
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'background_task',
'frontend',
]

In my tasks.py:

@background(schedule=30)
def check_q():
logger.debug("checking the queues - %s" % time.ctime())
print ("checking the queues")

If I comment out the background line, everything starts up fine. So I'm stumped...

Am I missing something here? I've been fighting this for an hour or so, with no luck.

   - Benjamin

Running on bschollnicklt
wq1 init
Unhandled exception in thread started by <function check_errors..wrapper at 0x038E5738>
Traceback (most recent call last):
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\compat\models.py", line 3, in
from compat import GenericForeignKey
ImportError: cannot import name 'GenericForeignKey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
fn(*args, **kwargs)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\core\management\commands\runserver.py", line 11
2, in inner_run
autoreload.raise_last_exception()
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_e
xception
raise exception[1]
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\core\management_init.py", line 327, in exec
ute
autoreload.check_errors(django.setup)()
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
fn(*args, **kwargs)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django_init_.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 89, in populate
app_config = AppConfig.create(entry)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\config.py", line 90, in create
module = import_module(entry)
File "C:\Users\bschollnick\python3\workqueues\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in load_unlocked
File "", line 678, in exec_module
File "", line 219, in call_with_frames_removed
File "C:\Users\bschollnick\Documents\wq1\frontend_init.py", line 3, in
import frontend.tasks
File "C:\Users\bschollnick\Documents\wq1\frontend\tasks.py", line 8, in
@background(schedule=30)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task_init.py", line 7, in background
from background_task.tasks import tasks
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task\tasks.py", line 16, in
from background_task.models import Task
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\background_task\models.py", line 10, in
from compat.models import GenericForeignKey
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\compat\models.py", line 5, in
from django.contrib.contenttypes.fields import GenericForeignKey
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\contrib\contenttypes\fields.py", line 3, in
from django.contrib.contenttypes.models import ContentType
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\contrib\contenttypes\models.py", line 134, in <
module>
class ContentType(models.Model):
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\db\models\base.py", line 100, in __new__app_config = apps.get_containing_app_config(module)
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
self.check_apps_ready()
File "C:\Users\bschollnick\python3\workqueues\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by philippeowagner** [comment]
#121 is closed, closing this

**Comment by LefterisJP** [comment]
Why was this issue closed @philippeowagner?  I am having the same problem and as the OP stated `django.ctronib.contenttypes` is in his `INSTALLED_APPS`. So the solution for #121 does not seem to apply here.
