### ISSUE TITLE
TransactionManagementError (again)

### ISSUE THREAD

**Issue by ADR-007** [arteria/django-background-tasks#158]
I have few repeated tasks that write something to the database
And when I run: `python manage.py process_tasks` I see few succesful tasks runs and then:

```Rescheduling energy_meters.tasks.detailed_energy_history_fetch_all
Traceback (most recent call last):
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 47, in bg_runner
    task.increment_attempts()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 221, in increment_attempts
    self.save()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 312, in save
    return super(Task, self).save(*arg, **kw)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1379, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
Traceback (most recent call last):
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 47, in bg_runner
    task.increment_attempts()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 221, in increment_attempts
    self.save()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 312, in save
    return super(Task, self).save(*arg, **kw)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1379, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/management/commands/process_tasks.py", line 94, in handle
    if not self._tasks.run_next_task(queue):
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 134, in run_next_task
    return self._runner.run_next_task(self, queue)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 260, in run_next_task
    self.run_task(tasks, task)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 251, in run_task
    tasks.run_task(task)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 131, in run_task
    self._bg_runner(proxy_task, task, *args, **kwargs)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/tasks.py", line 59, in bg_runner
    task.reschedule(t, e, traceback)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 236, in reschedule
    self.increment_attempts()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 221, in increment_attempts
    self.save()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/background_task/models.py", line 312, in save
    return super(Task, self).save(*arg, **kw)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1379, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/home/adrian/projects/samsung-school/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```
I just comment the `@atomic` decorator in `tasks.py` to fix it (but, of course it will broke something after that):
```
    # @atomic
    def run_task(self, tasks, task):
      ...

    # @atomic
    def run_next_task(self, tasks, queue=None):
      ...
```

**Comment by philippeowagner** [comment]
https://github.com/arteria/django-background-tasks/commit/bd569f45c57413d6d45cff28065fb88c5392212b
