### ISSUE TITLE
Unable to import models_completed 

### ISSUE THREAD

**Issue by aschuster3** [arteria/django-background-tasks#18]
When making migrations, I ran into an issue where it wouldn't properly generate due to an issue with importing models_completed in your admins.py 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\management\_
_init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\management\_
_init__.py", line 312, in execute
    django.setup()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\__init__.py", lin
e 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\apps\registry.py"
, line 115, in populate
    app_config.ready()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\app
s.py", line 22, in ready
    self.module.autodiscover()
  File "C:\Program Files (x86)\Python\lib\site-packages\django\contrib\admin\__i
nit__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\utils\module_load
ing.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Program Files (x86)\Python\lib\importlib\__init__.py", line 109, in i
mport_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python\lib\site-packages\background_task\admin.py
", line 2, in <module>
    from models_completed import CompletedTask
ImportError: No module named 'models_completed'
```

I checked through and the module is definitely there, but it just wasn't getting read.  I fiddled around a bit, and found that the following change in admins.py fixed the issue and let migrations run:

```
from django.contrib import admin
# from models_completed import CompletedTask  << Old
from .models_completed import CompletedTask

from .models import Task


class TaskAdmin(admin.ModelAdmin):
    display_filter = ['task_name']
    list_display = ['task_name', 'task_params', 'run_at', 'priority', 'attempts']


admin.site.register(Task, TaskAdmin)
admin.site.register(CompletedTask)
```

I'd make a pull request, but I honestly don't know if this is just a me-problem.  I'm running Win7 x64 using Django 1.8.2

**Comment by philippeowagner** [comment]
Hi @aschuster3 
Thanks for reporting this! The best would be to refactor the complete module to [absolute imports](https://github.com/arteria/style-guide#absolute-and-relative-imports). It's not done yet consequently because we adopted this thing. Would be great, in case you intend to send a PR, to follow the guide mentioned above.

**Comment by philippeowagner** [comment]
Hi @aschuster3 
I updated sources. Could you please check if you still have the issue using the latest commit? 
We will release a new version after the tests are passing again.

**Comment by aschuster3** [comment]
Hey, so sorry to reply almost a month later!  Everything works, thank you!

**Comment by philippeowagner** [comment]
Good news @aschuster3 !

**Comment by daveisagit** [comment]
I have just upgrade via pip to the latest 1.2.5 and now not able to start my django server due to ModuleNotFoundError: No module named 'background_task.models_completed'
Im running Python 3.7.4, Django 3.0.2
I cant run manage migrate either, any suggestions?
