### ISSUE TITLE
Error when tried it put it on recursion

### ISSUE THREAD

**Issue by unknown-guy-1610** [arteria/django-background-tasks#231]
Hey hi,
I wanted a delay of 5 minutes and run the process forever. So, I couldn't find anything which does this job. So, I tried putting in this way :

`
@background(schedule=60*5)
def notify_user():
    notify_user()
    //some_function
   print('done')//for debugging
`
I was trying get output by running this command in a new terminal
`python3 manage.py process_tasks`

Then, I figured out this is not working. I went through few Issues to check if there is any way to do this. Then I got to know I can check logs.

`python manage.py process_tasks --settings vc1_project.settings --traceback --log-file log/worker.log --log-level DEBUG
`
And this is my log :

Traceback (most recent call last):
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'process_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/sandeep/Desktop/Corona-Virus-Backend/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'vc1_project'
 
I guess this is solvable error. Can you check this out if it is solvable?

**Comment by unknown-guy-1610** [comment]
Nm I solved it
