### ISSUE TITLE
OperationalError: no such table: background_task

### ISSUE THREAD

**Issue by Lillo96** [arteria/django-background-tasks#247]
Hello. I've this error: **"return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: background_task**" with django 3.0.6 and Python 3.7. Here facing problems when making makemigrations. I have already tried to reset the migrations but te problem persist. I have installed the library following the docs instructions: https://django-background-tasks.readthedocs.io/en/latest/

**Comment by xtlc** [comment]
I had the same issue, my workaround was to comment all `backgorund_tasks` related code, do the migrations and then uncomment it. Very unhappy about this approach, but works just fine.

**Comment by jmartens** [comment]
Same here when running `makemigrations background_task` or` showmigrations backgroud_task` on a clean sqlit db.

```
(venv) C:\Users\foo.bar\Code\dicom_monitoring\dicomecho>python manage.py showmigrations background_task
Traceback (most recent call last):
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: background_task

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\base.py", line 366, in execute
    self.check()
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\foo.bar\Code\dicom_monitoring\dicomecho\dicomecho\urls.py", line 28, in <module>
    path('', include('echo.urls')),
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\foo.bar\Code\dicom_monitoring\dicomecho\echo\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\foo.bar\Code\dicom_monitoring\dicomecho\echo\views.py", line 298, in <module>
    if not Task.objects.filter(verbose_name="echo").exists():
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\models\query.py", line 777, in exists
    return self.query.has_results(using=self.db)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\models\sql\query.py", line 538, in has_results
    return compiler.has_results()
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1124, in has_results
    return bool(self.execute_sql(SINGLE))
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\foo.bar\Code\dicom_monitoring\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: background_task

(venv) C:\Users\foo.bar\Code\dicom_monitoring\dicomecho>
```

Worst thing is it makes all other migration tasks fail and I have to do them explicitly manually as there is no way to exclude one module
