### ISSUE TITLE
error when trying to run 

### ISSUE THREAD

**Issue by exquest** [arteria/django-background-tasks#73]
I get a strange error. It seems some database table are missing or something...

I get this error when I try and run the process_tasks management command and when I try to add a background decorator to a function.

here is the error code I get:

`Traceback (most recent call last):
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "background_task" does not exist
LINE 1: ..."."locked_by", "background_task"."locked_at" FROM "backgroun...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/background_task/management/commands/process_tasks.py", line 108, in handle
    if not self._tasks.run_next_task(queue):
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/background_task/tasks.py", line 118, in run_next_task
    return self._runner.run_next_task(self, queue)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/background_task/tasks.py", line 242, in run_next_task
    task = self.get_task_to_run(tasks, queue)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/background_task/tasks.py", line 222, in get_task_to_run
    available_tasks = [task for task in Task.objects.find_available(queue)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/models/query.py", line 1085, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/anthony/.virtualenvs/headline_scraper/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "background_task" does not exist
LINE 1: ..."."locked_by", "background_task"."locked_at" FROM "backgroun...`

**Comment by jvamvas** [comment]
@exquest, try to call the `makemigrations` command explicitly for this app:

```
$ python manage.py makemigrations background_task
Migrations for 'background_task':
  0001_initial.py:
    - Create model CompletedTask
    - Create model Task
...
$ python manage.py migrate
```

**Comment by exquest** [comment]
Thanks. That fixes it.
