### ISSUE TITLE
Error on process_tasks command

### ISSUE THREAD

**Issue by SilvioMessi** [arteria/django-background-tasks#95]
Hi!
When I try to execute the  process_tasks command I get this error:
```
(ENV) iMac-di-Silvio:management_software_OCA messi$ python manage.py process_tasks
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/background_task/management/commands/process_tasks.py", line 80, in handle
    sig_manager = SignalManager()
  File "/Users/messi/Desktop/OCA/Implementazione/management_software_OCA/ENV/lib/python3.5/site-packages/background_task/utils.py", line 15, in __init__
    signal.signal(signal.SIGSTOP, self.exit_gracefully)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
OSError: [Errno 22] Invalid argument
```
Thank you,
Silvio

**Comment by walterrenner** [comment]
https://mail.python.org/pipermail/python-list/2011-November/615417.html

**Comment by SilvioMessi** [comment]
On my platform (OSX 10.12.4), using SIGINT instead of SIGSTOP allows me to stop (with ctrl+C) the command, calling the exit_gracefully function.

**Comment by han507** [comment]
my platform  is (OSX 10.11.6) and i got similar error below
`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/background_task/management/commands/process_tasks.py", line 80, in handle
    sig_manager = SignalManager()
  File "/Users/a1002350/.pyenv/versions/2.7.13/envs/compute_api/lib/python2.7/site-packages/background_task/utils.py", line 15, in __init__
    signal.signal(signal.SIGSTOP, self.exit_gracefully)
RuntimeError: (22, 'Invalid argument')
`

**Comment by raghavkhajuria** [comment]
Till when can we expect this to get sorted ?

**Comment by jenda1** [comment]
SIGTERM should be used instead. It is supported on all major platforms (Win, Unix). SIGSTOP is not supported on Windows and on Linux the signal can not be handled.

**Comment by walterrenner** [comment]
Please install v1.1.9 from the PyPI 📦 
https://pypi.python.org/pypi/django-background-tasks/1.1.9
